import type { TowerStats } from './types';

export const TOWER_LIST: TowerStats[] = [
  {
    id: 'scout',
    name: '스카웃',
    cost: 40,
    range: 3,
    damage: 2,
    fireRate: 1.2,
    projectileSpeed: 8,
    targeting: 'first',
  },
  {
    id: 'soldier',
    name: '솔져',
    cost: 90,
    range: 3,
    damage: 3,
    fireRate: 1.5,
    projectileSpeed: 9,
    targeting: 'first',
    burstCount: 3,
    burstIntervalSec: 0.1,
  },
  {
    id: 'sniper',
    name: '스나이퍼',
    cost: 150,
    range: 8,
    damage: 15,
    fireRate: 0.4,
    projectileSpeed: 14,
    targeting: 'strongest',
  },
  {
    id: 'minigunner',
    name: '미니거너',
    cost: 160,
    range: 5,
    damage: 6,
    fireRate: 6,
    projectileSpeed: 10,
    targeting: 'first',
    spinUpSec: 2,
  },
  {
    id: 'flamethrower',
    name: '화염방사병',
    cost: 110,
    range: 1.8,
    damage: 1,
    fireRate: 2,
    projectileSpeed: 6,
    targeting: 'closest',
    splashRadius: 1,
    burnDurationSec: 5,
    burnTickIntervalSec: 1,
    burnDamagePerTick: 3,
  },
  {
    id: 'commander',
    name: '사령관',
    cost: 130,
    range: 3,
    damage: 0,
    fireRate: 0,
    projectileSpeed: 0,
    targeting: 'first',
    support: { buffPercent: 0.3 },
  },
  {
    id: 'dj',
    name: 'DJ',
    cost: 200,
    range: 3,
    damage: 0,
    fireRate: 0,
    projectileSpeed: 0,
    targeting: 'first',
    support: { buffPercent: 0.5, modes: ['range', 'damage', 'discount'] },
  },
];

export const TOWERS_BY_ID: Record<string, TowerStats> = Object.fromEntries(
  TOWER_LIST.map((tower) => [tower.id, tower])
);
